name: Node Continuous Integration

on:
  pull_request:
<<<<<<< HEAD
    branches: [ master ]
=======
    branches: [ main ]
>>>>>>> ad04cc729cb8db76bc8b25284dd264c8e0c3c153


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
<<<<<<< HEAD
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
=======
          node-version: 23
      - run: npm ci
      - run: npm test
      - run: npm run build
>>>>>>> ad04cc729cb8db76bc8b25284dd264c8e0c3c153
